# Navigation Links

main:
  - name: Research
    url: research
    weight: 10

  - name: People
    url: people
    weight: 20

  - name: Publications
    url: publication
    weight: 30

  - name: Contact
    url: contact
    weight: 40
